config/routes.rb
Rails.application.routes.draw do

  get "application/index"
  get "works/tree"
  get "works/old_tree"
  get "works/jsontree"
  get "works/by_medium"
  get "works/by_location"  
  get "pages/map_concept"
  get "pages/about"
  get "pages/essays"
  get "pages/essay_nathan_langston"
  get "pages/essay_peter_crack"
  get "pages/essay_lindsey_allgood"
  get "pages/links"
  get "pages/sponsors"  
  resources :works
  resources :artists
  resources :curated_tours do
    resources :curated_tour_stops 
  end   
  # You can have the root of your site routed with "root"
  root 'application#index'

  # Admin Interface
  namespace :admin do
    # Directs /admin/artists/* to Admin::ArtistsController
    # (app/controllers/admin/artist_controller.rb)
    resources :works
    resources :work_representations
    resources :artists
    resources :curated_tour_stops
    resources :curated_tours
    get "data/import_spreadsheet"
    get "data/import_bios"    
    get "data/import_work_representations"
    get "data/populate_tour"
    get "data/tests"
    get "works/tree"
    get "works/jsontree"
    get "application/index"
    root 'application#index'
  end
  
end

app/models/curated_tour.rb
class CuratedTour < ActiveRecord::Base
  has_many :curated_tour_stop
end

app/controllers/admin/curated_tours_controller.rb
class Admin::CuratedToursController < Admin::ApplicationController
  before_action :set_curated_tour, only: [:show, :edit, :update, :destroy]

  # GET /admin/curated_tours
  def index
    @curated_tours = CuratedTour.all
  end

  # GET /admin/curated_tours/1
  def show
  end

  # GET /admin/curated_tours/new
  def new
    @curated_tour = CuratedTour.new
  end

  # GET /admin/curated_tours/1/edit
  def edit
  end

  # POST /admin/curated_tours
  def create
    @curated_tour = CuratedTour.new(curated_tour_params)

    if @curated_tour.save
      redirect_to [:admin, @curated_tour], notice: 'Curated tour was successfully created.'
    else
      render action: 'new'
    end
  end

  # PATCH/PUT /admin/curated_tours/1
  def update
    if @curated_tour.update(curated_tour_params)
      redirect_to [:admin, @curated_tour], notice: 'Curated tour was successfully updated.'
    else
      render action: 'edit'
    end
  end

  # DELETE /admin/curated_tours/1
  def destroy
    @curated_tour.destroy
    redirect_to admin_curated_tours_url, notice: 'Curated tour was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_curated_tour
      @curated_tour = CuratedTour.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def curated_tour_params
      params.require(:curated_tour).permit(:tour_author, :tour_name, :published)
    end
end

app/controllers/curated_tours_controller.rb
class CuratedToursController < ApplicationController
  before_action :set_curated_tours, only: [:show]

  caches_action :index, :show

  # GET /curated_tours
  def index
    @curated_tours = CuratedTour.all
  end

  # GET /curated_tours/1
  def show
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_curated_tours
      @curated_tour = CuratedTour.find(params[:id])
    end

end

app/helpers/admin/curated_tours_helper.rb
module Admin::CuratedToursHelper
end

app/helpers/curated_tours_helper.rb
module CuratedToursHelper
end

app/views/admin/curated_tours/_form.html.erb
<%= form_for([:admin, @curated_tour]) do |f| %>
  <% if @curated_tour.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@curated_tour.errors.count, "error") %> prohibited this curated_tour from being saved:</h2>

      <ul>
      <% @curated_tour.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
      <%= f.label :tour_author %><br>
    <%= f.text_field :tour_author %>
    </div>
  <div class="field">
      <%= f.label :tour_name %><br>
    <%= f.text_field :tour_name %>
    </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/admin/curated_tours/edit.html.erb
<h1>Editing curated_tour</h1>

<%= render 'form' %>

<%= link_to 'Show', [:admin, @curated_tour] %> |
<%= link_to 'Back', admin_curated_tours_path %>

app/views/admin/curated_tours/index.html.erb
<h1>Listing Curated Tours</h1>

<table>
  <thead>
    <tr>
      <th>Tour Author</th>
      <th>Tour Name</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @curated_tours.each do |curated_tour| %>
      <tr>
        <td><%= curated_tour.tour_author %></td>
        <td><%= curated_tour.tour_name %></td>
        <td><%= link_to 'Show', [:admin, curated_tour] %></td>
        <td><%= link_to 'Edit', edit_admin_curated_tour_path(curated_tour) %></td>
        <td><%= link_to 'Destroy', [:admin, curated_tour], method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Curated tour', new_admin_curated_tour_path %>

app/views/admin/curated_tours/new.html.erb
<h1>New curated_tour</h1>

<%= render 'form' %>

<%= link_to 'Back', admin_curated_tours_path %>

app/views/admin/curated_tours/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Tour author:</strong>
  <%= @curated_tour.tour_author %>
</p>

<p>
  <strong>Tour name:</strong>
  <%= @curated_tour.tour_name %>
</p>


<%= link_to 'Edit', edit_admin_curated_tour_path(@curated_tour) %> |
<%= link_to 'Back', admin_curated_tours_path %>