config/routes.rb
Rails.application.routes.draw do

  get "application/index"
  get "works/tree"
  get "works/old_tree"
  get "works/jsontree"
  get "works/by_medium"
  get "works/by_location"  
  get "pages/map_concept"
  get "pages/about"
  get "pages/essays"
  get "pages/essay_nathan_langston"
  get "pages/essay_peter_crack"
  get "pages/essay_lindsey_allgood"
  get "pages/links"
  get "pages/sponsors"  
  resources :works
  resources :artists
  resources :curated_tours do
    resources :curated_tour_stops 
  end   
  # You can have the root of your site routed with "root"
  root 'application#index'

  # Admin Interface
  namespace :admin do
    # Directs /admin/artists/* to Admin::ArtistsController
    # (app/controllers/admin/artist_controller.rb)
    resources :works
    resources :work_representations
    resources :artists
    resources :curated_tour_stops
    resources :curated_tours
    get "data/import_spreadsheet"
    get "data/import_bios"    
    get "data/import_work_representations"
    get "data/populate_tour"
    get "data/tests"
    get "works/tree"
    get "works/jsontree"
    get "application/index"
    root 'application#index'
  end
  
end

app/models/curated_tour_stop.rb
class CuratedTourStop < ActiveRecord::Base
  belongs_to :work
  belongs_to :curated_tour
  acts_as_sequenced scope: :curated_tour_id
end

app/controllers/admin/curated_tour_stops_controller.rb
class Admin::CuratedTourStopsController < Admin::ApplicationController
  before_action :set_curated_tour_stop, only: [:show, :edit, :update, :destroy]

  # GET /admin/curated_tour_stops
  def index
    @curated_tour_stops = CuratedTourStop.order('curated_tour_stops.curated_tour_id, curated_tour_stops.sequential_id').all
  end

  # GET /admin/curated_tour_stops/1
  def show
  end

  # GET /admin/curated_tour_stops/new
  def new
    @curated_tour_stop = CuratedTourStop.new
  end

  # GET /admin/curated_tour_stops/1/edit
  def edit
  end

  # POST /admin/curated_tour_stops
  def create
    @curated_tour_stop = CuratedTourStop.new(curated_tour_stop_params)

    if @curated_tour_stop.save
      redirect_to [:admin, @curated_tour_stop], notice: 'Curated tour stop was successfully created.'
    else
      render action: 'new'
    end
  end

  # PATCH/PUT /admin/curated_tour_stops/1
  def update
    if @curated_tour_stop.update(curated_tour_stop_params)
      redirect_to [:admin, @curated_tour_stop], notice: 'Curated tour stop was successfully updated.'
    else
      render action: 'edit'
    end
  end

  # DELETE /admin/curated_tour_stops/1
  def destroy
    @curated_tour_stop.destroy
    redirect_to admin_curated_tour_stops_url, notice: 'Curated tour stop was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_curated_tour_stop
      @curated_tour_stop = CuratedTourStop.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def curated_tour_stop_params
      params.require(:curated_tour_stop).permit(:caption_text, :sequential_id, :work_id, :curated_tour_id)
    end
end

app/controllers/curated_tour_stops_controller.rb
class CuratedTourStopsController < ApplicationController
  before_action :set_curated_tour, only: [:show]
  before_action :set_curated_tour_stops, only: [:show]
  
  caches_action :index, :show
  
  # GET /curated_tour_stops
  def index
    @curated_tour_stops = CuratedTourStop.order('curated_tour_stops.curated_tour_id, curated_tour_stops.sequential_id').all
  end

  # GET /curated_tour_stops/1
  def show
     @curated_tour_stops_count = @curated_tour.curated_tour_stop.count  
     @markdown = Redcarpet::Markdown.new(Redcarpet::Render::HTML, :autolink => true, :space_after_headers => true)
  end

  private

    def set_curated_tour
      @curated_tour = CuratedTour.find(params[:curated_tour_id])
    end

    def set_curated_tour_stops
      @curated_tour_stop = @curated_tour.curated_tour_stop.where(:sequential_id => params[:id]).first
    end

end

app/helpers/admin/curated_tour_stops_helper.rb
module Admin::CuratedTourStopsHelper
end

app/helpers/curated_tour_stops_helper.rb
module CuratedTourStopsHelper
end

app/views/admin/curated_tour_stops/_form.html.erb
<%= form_for([:admin, @curated_tour_stop]) do |f| %>
  <% if @curated_tour_stop.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@curated_tour_stop.errors.count, "error") %> prohibited this curated_tour_stop from being saved:</h2>

      <ul>
      <% @curated_tour_stop.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field big">
      <%= f.label :caption_text %><br>
    <%= f.text_area :caption_text %>
    </div>
  <div class="field">
      <%= f.label :sequential_id %><br>
    <%= f.number_field :sequential_id %>
    </div>
  <div class="field">
    <%= f.label :work_id %><br>
    <%= f.collection_select :work_id, Work.all(:order => "title"), :id, :title, :include_blank => true %>
  </div>
  <div class="field">
    <%= f.label :curated_tour %><br>
    <%= f.collection_select :curated_tour_id, CuratedTour.all(:order => "tour_name"), :id, :tour_name, :include_blank => true %>
  </div>		
		
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/admin/curated_tour_stops/edit.html.erb
<h1>Editing curated_tour_stop</h1>

<%= render 'form' %>

<%= link_to 'Show', [:admin, @curated_tour_stop] %> |
<%= link_to 'Back', admin_curated_tour_stops_path %>

app/views/admin/curated_tour_stops/index.html.erb
<h1>Listing curated_tour_stops</h1>

<table>
  <thead>
    <tr>
      <th>Tour</th>
      <th>Stop #</th>
      <th>Caption Text</th>     
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @curated_tour_stops.each do |curated_tour_stop| %>
      <tr>
        <td><%= curated_tour_stop.curated_tour.tour_name %></td>
        <td><%= curated_tour_stop.sequential_id %></td>
        <td><%= truncate(curated_tour_stop.caption_text, length: 35, omission: '...') %></td>
        <td><%= link_to 'Show', [:admin, curated_tour_stop] %></td>
        <td><%= link_to 'Edit', edit_admin_curated_tour_stop_path(curated_tour_stop) %></td>
        <td><%= link_to 'Destroy', [:admin, curated_tour_stop], method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Curated tour stop', new_admin_curated_tour_stop_path %>

app/views/admin/curated_tour_stops/new.html.erb
<h1>New curated_tour_stop</h1>

<%= render 'form' %>

<%= link_to 'Back', admin_curated_tour_stops_path %>

app/views/admin/curated_tour_stops/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Caption text:</strong>
  <%= @curated_tour_stop.caption_text %>
</p>

<p>
  <strong>Sequential:</strong>
  <%= @curated_tour_stop.sequential_id %>
</p>

<p>
  <strong>Work:</strong>
  <%= @curated_tour_stop.work %>
</p>

<p>
  <strong>Curated tour:</strong>
  <%= @curated_tour_stop.curated_tour %>
</p>

<%= link_to 'Edit', edit_admin_curated_tour_stop_path(@curated_tour_stop) %> |
<%= link_to 'Back', admin_curated_tour_stops_path %>