config/routes.rb
Rails.application.routes.draw do

  get "application/index"
  get "works/tree"
  get "works/old_tree"
  get "works/jsontree"
  get "works/by_medium"
  get "works/by_location"  
  get "pages/map_concept"
  get "pages/about"
  get "pages/essays"
  get "pages/essay_nathan_langston"
  get "pages/essay_peter_crack"
  get "pages/essay_lindsey_allgood"
  get "pages/links"
  get "pages/sponsors"  
  resources :works
  resources :artists
  resources :curated_tours do
    resources :curated_tour_stops 
  end   
  # You can have the root of your site routed with "root"
  root 'application#index'

  # Admin Interface
  namespace :admin do
    # Directs /admin/artists/* to Admin::ArtistsController
    # (app/controllers/admin/artist_controller.rb)
    resources :works
    resources :work_representations
    resources :artists
    resources :curated_tour_stops
    resources :curated_tours
    get "data/import_spreadsheet"
    get "data/import_bios"    
    get "data/import_work_representations"
    get "data/populate_tour"
    get "data/tests"
    get "works/tree"
    get "works/jsontree"
    get "application/index"
    root 'application#index'
  end
  
end

app/models/artist.rb
class Artist < ActiveRecord::Base
  has_many :works
  
  def longname?
    nameList = self.name.split(" ")
    longname = false
    nameList.each do |nameToken|
      if nameToken.length > 9
        longname = true
      end
    end
    return longname
  end
end

app/controllers/admin/artists_controller.rb
class Admin::ArtistsController < Admin::ApplicationController
  before_action :set_artist, only: [:show, :edit, :update, :destroy]

  # GET /artists
  def index
    @artists = Artist.all
  end

  # GET /artists/1
  def show
  end

  # GET /artists/new
  def new
    @artist = Artist.new
  end

  # GET /artists/1/edit
  def edit
  end

  # POST /artists
  def create
    @artist = Artist.new(artist_params)

    if @artist.save
      redirect_to [:admin, @artist], notice: 'Artist was successfully created.'
    else
      render action: 'new'
    end
  end

  # PATCH/PUT /artists/1
  def update
    if @artist.update(artist_params)
      redirect_to [:admin, @artist], notice: 'Artist was successfully updated.'
    else
      render action: 'edit'
    end
  end

  # DELETE /artists/1
  def destroy
    @artist.destroy
    redirect_to admin_artists_url, notice: 'Artist was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_artist
      @artist = Artist.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def artist_params
      params.require(:artist).permit(:name, :contact, :bio, :url, :location)
    end
end

app/controllers/artists_controller.rb
class ArtistsController < ApplicationController
  before_action :set_artist, only: [:show, :edit, :update, :destroy]

  # GET /artists
  def index
    @artists = Artist.order('artists.name ASC').all
    @markdown = Redcarpet::Markdown.new(Redcarpet::Render::HTML, :autolink => true, :space_after_headers => true) 
  end

  # GET /artists/1
  def show
    @work = Work.find_by_artist_id(params[:id])
    @markdown = Redcarpet::Markdown.new(Redcarpet::Render::HTML, :autolink => true, :space_after_headers => true) 
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_artist
      @artist = Artist.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def artist_params
      params.require(:artist).permit(:name, :contact, :bio, :url, :location)
    end
end

app/helpers/admin/artists_helper.rb
module Admin::ArtistsHelper
end

app/helpers/artists_helper.rb
module ArtistsHelper
end

app/views/admin/artists/_form.html.erb
<%= form_for([:admin, @artist]) do |f| %>
  <% if @artist.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@artist.errors.count, "error") %> prohibited this artist from being saved:</h2>

      <ul>
      <% @artist.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_area :name %>
  </div>
  <div class="field">
    <%= f.label :contact %><br>
    <%= f.text_area :contact %>
  </div>
  <div class="field big">
    <%= f.label :bio %><br>
    <%= f.text_area :bio %>
  </div>
  <div class="field">
    <%= f.label :url %><br>
    <%= f.text_area :url %>
  </div>
  <div class="field">
    <%= f.label :location %><br>
    <%= f.text_area :location %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/admin/artists/edit.html.erb
<h1>Editing artist</h1>

<%= render 'form' %>

<%= link_to 'Show', @artist %> |
<%= link_to 'Back', admin_artists_path %>

app/views/admin/artists/index.html.erb
<h1>Listing artists</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Contact</th>
      <th>Bio</th>
      <th>Url</th>
      <th>Location</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @artists.each do |artist| %>
      <tr>
        <td><%= artist.name %></td>
        <td><%= artist.contact %></td>
        <td><%= artist.bio %></td>
        <td><%= artist.url %></td>
        <td><%= artist.location %></td>
        <td><%= link_to 'Show', [:admin, artist] %></td>
        <td><%= link_to 'Edit', edit_admin_artist_path(artist) %></td>
        <td><%= link_to 'Destroy', [:admin, artist], method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Artist', new_admin_artist_path %>

app/views/admin/artists/new.html.erb
<h1>New artist</h1>

<%= render 'form' %>

<%= link_to 'Back', admin_artists_path %>

app/views/admin/artists/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @artist.name %>
</p>

<p>
  <strong>Contact:</strong>
  <%= @artist.contact %>
</p>

<p>
  <strong>Bio:</strong>
  <%= @artist.bio %>
</p>

<p>
  <strong>Url:</strong>
  <%= @artist.url %>
</p>

<p>
  <strong>Location:</strong>
  <%= @artist.location %>
</p>

<%= link_to 'Edit', edit_admin_artist_path(@artist) %> |
<%= link_to 'Back', admin_artists_path %>