config/routes.rb
Rails.application.routes.draw do

  get "application/index"
  get "works/tree"
  get "works/old_tree"
  get "works/jsontree"
  get "works/by_medium"
  get "works/by_location"  
  get "pages/map_concept"
  get "pages/about"
  get "pages/essays"
  get "pages/essay_nathan_langston"
  get "pages/essay_peter_crack"
  get "pages/essay_lindsey_allgood"
  get "pages/links"
  get "pages/sponsors"  
  resources :works
  resources :artists
  resources :curated_tours do
    resources :curated_tour_stops 
  end   
  # You can have the root of your site routed with "root"
  root 'application#index'

  # Admin Interface
  namespace :admin do
    # Directs /admin/artists/* to Admin::ArtistsController
    # (app/controllers/admin/artist_controller.rb)
    resources :works
    resources :work_representations
    resources :artists
    resources :curated_tour_stops
    resources :curated_tours
    get "data/import_spreadsheet"
    get "data/import_bios"    
    get "data/import_work_representations"
    get "data/populate_tour"
    get "data/tests"
    get "works/tree"
    get "works/jsontree"
    get "application/index"
    root 'application#index'
  end
  
end

app/models/work.rb
class Work < ActiveRecord::Base
  acts_as_sane_tree
  belongs_to :artist
  has_many :work_representations, -> { order(:created_at) }
  
  def self.random
    order('RANDOM()').first
  end  
end

app/controllers/admin/works_controller.rb
class Admin::WorksController < Admin::ApplicationController
  before_action :set_work, only: [:show, :edit, :update, :destroy]

  # GET /works
  def index
    @works = Work.all
  end

  # GET /works/tree
  def tree
    rootWork = Work.find_by_parent_id(nil)
    @treehtml = '<ul>' + generate_nested_list(rootWork) + '</ul>'
  end
  
  # GET /works/jsontree
  def jsontree
    rootWork = Work.all#Work.find_by_parent_id(nil)
    @treehtml = rootWork
  end  
  
  def generate_nested_list (node)
    ghtml = '<li><a>&nbsp;</a><span><a href="/works/%s" class="%s">%s</a></span>'%[node.id, node.medium, node.title]
    unless node.children.empty?
      ghtml << '<ul>'
      node.children.each do |childnode|
        ghtml << generate_nested_list(childnode)
      end
      ghtml << '</ul>'
    end
    ghtml << '</li>'
    ghtml
  end
  
  # GET /works/1
  def show
    @markdown = Redcarpet::Markdown.new(Redcarpet::Render::HTML, :autolink => true, :space_after_headers => true)  
  end
  
  # GET /works/new
  def new
    @work = Work.new
  end

  # GET /works/1/edit
  def edit
  end

  # POST /works
  def create
    @work = Work.new(work_params)

    if @work.save
      redirect_to [:admin, @work], notice: 'Work was successfully created.'
    else
      render action: 'new'
    end
  end

  # PATCH/PUT /works/1
  def update
    if @work.update(work_params)
      redirect_to [:admin, @work], notice: 'Work was successfully updated.'
    else
      render action: 'edit'
    end
  end

  # DELETE /works/1
  def destroy
    @work.destroy
    redirect_to admin_works_url, notice: 'Work was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_work
      @work = Work.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def work_params
      params.require(:work).permit(:title, :parent_id, :artist_id, :medium)
    end
end

app/controllers/works_controller.rb
class WorksController < ApplicationController

  before_action :set_work, only: [:show, :edit, :update, :destroy]

  caches_action :index, :by_medium, :by_location, :tree, :show, :old_tree, :jsontree
  
  # GET /works
  def index
    @works = Work.all
  end

  # GET /works/1
  def show
    @artist = Artist.find_by_id(@work.artist_id);
    if @work.children.empty?
      @random = Work.random
    end
    @markdown = Redcarpet::Markdown.new(Redcarpet::Render::HTML, :autolink => true, :space_after_headers => true)  
    
    populate_social_urls
    set_facebook_og_meta
    set_twitter_card_meta
  end

  # GET /works/by_medium
  def by_medium
    @media = Work.all.pluck(:medium)
  
    @media_collection = Hash.new
    @media.each do |medium| 
        @media_collection[medium] = Work.where(:medium => medium)
    end
  end  
  
  # GET /works/by_location
  def by_location
    @locations = Artist.pluck(:location)  
    @location_collection = Hash.new
    
    @color_steps = get_color_steps @locations.count
    
    @locations.each do |location|
      @location_collection[location] = Work.joins(:artist).where('artists.location = ?', location);
    end
    
    @countries = @locations.uniq {|location| location.split(', ').last }    
  end    
  
  # GET /works/tree
  def tree
    @works = Work.all
  end  
  
  # GET /works/old_tree
  def old_tree
    rootWork = Work.find_by_parent_id(nil)
    @treehtml = '<ul>' + generate_nested_list(rootWork) + '</ul>'
  end
  
  # GET /works/jsontree
  def jsontree
    render json: Work.all.to_json(
      :only  => [:id, :medium],
      :include => {:artist => {
        :only => [:name, :location]
    }})
  end  
  
  def generate_nested_list (node)
    ghtml = '<li><a>&nbsp;</a><span><a href="/works/%s" class="%s">%s</a></span>'%[node.id, node.medium, node.title]
    unless node.children.empty?
      ghtml << '<ul>'
      node.children.each do |childnode|
        ghtml << generate_nested_list(childnode)
      end
      ghtml << '</ul>'
    end
    ghtml << '</li>'
    ghtml
  end

  private

    # comb through a work to find its 
    def populate_social_urls
      @social_work_url = url_for(:controller => :works, :only_path => false)+'/'+@work.id.to_s;
      @social_work_title = "TELEPHONE #{@work.medium.downcase} work by #{@artist.name}"
      @social_work_description = "#{@artist.name} created this work as a part of the international art game TELEPHONE.  315 artists in 43 countries participated."
      
      @default_image_url = request.protocol + request.host_with_port + view_context.image_path('TelephoneSatelliteCollectiveSocialWork2.png')
      
      @social_image_url = false
      @debug = []
      @work.work_representations.each do |wr|
        if ['gif','jpg','png'].include?(wr.fileext.downcase) && !@social_image_url then @social_image_url = view_context.work_image_url(wr.url, :lightbox, false) end
      end
 
      if !@social_image_url then @social_image_url = @default_image_url end
    end

    # set facebook og: metadata for works on the site
    def set_facebook_og_meta      
      og = {
        :title        => @social_work_title,
        :description  => @social_work_description,
        :type         => 'website',
        :url          => @social_work_url
      }   
      
      if @social_image_url.is_a? String then og[:image] = @social_image_url end
      
      set_meta_tags :og => og
    end
      
    # set twitter card metadata for works on the site  
    def set_twitter_card_meta
      twitter = {
        :card  => 'summary',
        :site  => '@Sat_Collective',
        :title        => @social_work_title,
        :description  => @social_work_description,
        :image => @social_image_url
      }
      
      set_meta_tags :twitter => twitter
    end
  
    # Get color steps for the custom by_location headers
    def get_color_steps(total)
      # set up color transition
      startHSV   = {:h => 342, :s => 98.5, :v => 79.6}
      endHSV     = {:h => 194, :s => 95.7, :v => 91.0}
      
      diffHSV = {
        :h => (startHSV[:h] - endHSV[:h]), 
        :s => (startHSV[:s] - endHSV[:s]), 
        :v => (startHSV[:v] - endHSV[:v])
        } 
      increment = {}
      increment[:h] = diffHSV[:h].to_f / total
      increment[:s] = diffHSV[:s].to_f / total
      increment[:v] = diffHSV[:v].to_f / total
      
      lastStep = startHSV.dup
      steps = []
      steps << to_hsl_string(lastStep)
      (total - 1).times do 
        lastStep = { 
          :h => (lastStep[:h] - increment[:h]).round(2),
          :s => (lastStep[:s] - increment[:s]).round(2),  
          :v => (lastStep[:v] - increment[:v]).round(2)    
          }
        steps << to_hsl_string(lastStep)
      end
      steps << to_hsl_string(endHSV)
      steps
    end
  
    # Initialize a color based on RGB values. By default, the values
    # should be between 0 and 255. If you use the option <tt>:percent => true</tt>,
    # the values should then be between 0.0 and 1.0.
    def to_hsl_string(hsv_hash)
      
      hsl_hash = {}
      
      # determine the lightness in the range [0,100]
      hsl_hash[:l] = (2 - hsv_hash[:s] / 100) * hsv_hash[:v] / 2;
  
      l_calculation = (hsl_hash[:l] < 50 ? hsl_hash[:l] * 2 : 200 - hsl_hash[:l] * 2)
  
      # store the HSL components
      hsl_hash[:h] = hsv_hash[:h]
      hsl_hash[:s] = hsv_hash[:s] * ((l_calculation.nonzero?)?(hsv_hash[:v] / l_calculation):0)

      (hsl_hash[:h]).round.to_s + ',' + (hsl_hash[:s]).round.to_s + '%,' + (hsl_hash[:l]).round.to_s + '%'
    end
  
    # Use callbacks to share common setup or constraints between actions.
    def set_work
      @work = Work.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def work_params
      params.require(:work).permit(:title, :parent_id, :artist_id, :medium)
    end
end

app/helpers/admin/works_helper.rb
module Admin::WorksHelper
end

app/helpers/works_helper.rb
require 'csv'

module WorksHelper
  
  # get the url for an image work representation
  def work_image_url(original_path, size = :work_show, use_image_server = true)
    returnpath = original_path.dup
    
    # replace the original image URL with its resized version path (I know, it's ugly)
    if size == :work_show
      replacer_array = {
        "/0" => "/540/0",
        ".jpg" => "_540.jpg",
        ".png" => "_540.jpg",
        ".gif" => "_540.gif"
      }      
    elsif size == :lightbox
      replacer_array = {
        "/0" => "/960/0",
        ".jpg" => "_960x620.jpg",
        ".png" => "_960x620.jpg",
        ".gif" => "_960x620.gif"
      }      
    end
    
    # replace the satellite collective asset URL with an AWS URL if available
    if ENV['ASSET_URL_SATELLITECOLLECTIVE'] && ENV['ASSET_URL_AWS_S3'] && use_image_server
      replacer_array[ENV['ASSET_URL_SATELLITECOLLECTIVE']] = ENV['ASSET_URL_AWS_S3']
    end
  
    replacer_array.each do |find, replace|
      returnpath = returnpath.sub find, replace
    end    
    
    returnpath           
  end
  
  # get an image tag for an image work representation
  def work_image_tag(original_path, size = :work_show, use_image_server = true)
    image_tag work_image_url(original_path, size, use_image_server)   
  end
  
  # hack to get treeview hover boxes to appear above or below the cursor properly
  def position_by_top_or_bottom(position)
    highest_position_that_needs_adjustment = 400
    if position.to_i > lowest_position_to_use_top
      return 'bottom'
    end
  end
  
  # if boxes are too low to the bottom they need to be moved up +
  def adjust_x_coord_for_height(height)
    y_coords_below_this_need_adjustment = 500
    if height.to_i > y_coords_below_this_need_adjustment
      return height - 200
    else 
      return height     
    end
  end

  # hacky way to get the coordinates for the image map for each work id
  def get_coordinates_for_work_id(work_id)
    
    coordinate_data = get_coordinate_data()
    coordinate_data.each do |data|
      if data[0].strip.to_i == work_id          
        return [data[1], data[2]]
      end
    end
    return [1,1]    
  end
  
  def get_coordinate_data()
    CSV.parse(<<-ENDDATA
    1,400,390
    2,408,356
    3,408,424
    4,373,413
    5,432,328
    6,351,440
    7,431,453
    8,388,459
    9,357,295
    10,453,299
    11,505,381
    12,261,377
    13,358,257
    14,458,263
    15,511,305
    16,523,323
    17,540,382
    18,229,423
    19,226,385
    20,232,343
    21,289,255
    22,335,229
    23,357,220
    24,397,215
    25,379,181
    26,395,181
    27,410,181
    28,452,223
    29,473,231
    30,490,240
    31,509,252
    32,527,271
    33,539,284
    34,549,298
    35,206,470
    36,197,442
    37,191,405
    38,190,392
    39,191,374
    40,196,343
    41,203,320
    42,228,269
    43,254,239
    44,294,209
    45,314,199
    46,340,189
    47,421,146
    48,434,148
    49,382,145
    50,395,145
    51,357,149
    52,463,190
    53,478,195
    54,570,265
    55,167,465
    56,162,448
    57,159,432
    58,208,239
    59,231,214
    60,248,198
    61,285,173
    62,297,168
    63,307,163
    64,328,194
    65,540,407
    66,138,485
    67,206,189
    68,218,178
    69,230,168
    70,241,159
    71,428,182
    72,447,186
    73,188,512
    74,179,496
    75,173,481
    76,131,468
    77,127,450
    78,167,179
    79,175,170
    80,184,161
    81,195,150
    82,240,118
    83,258,109
    84,289,132
    85,414,111
    86,428,112
    87,557,313
    88,516,216
    89,564,329
    90,207,141
    91,155,391
    92,527,222
    93,535,230
    94,156,375
    95,158,356
    96,493,441
    97,468,469
    98,443,486
    99,418,494
    100,402,495
    101,381,493
    102,516,468
    103,505,483
    104,490,497
    105,569,345
    106,545,238
    107,160,341
    108,574,365
    109,574,396
    110,153,142
    111,165,131
    112,224,88
    113,572,418
    114,160,534
    115,329,120
    116,164,327
    117,165,237
    118,331,469
    119,121,402
    120,150,518
    121,130,315
    122,371,147
    123,123,352
    124,315,451
    125,263,187
    126,331,154
    127,344,151
    128,589,297
    129,478,507
    130,594,308
    131,126,335
    132,598,320
    133,315,501
    134,536,424
    135,463,515
    136,124,434
    137,143,501
    138,377,529
    139,303,491
    140,531,440
    141,175,123
    142,476,158
    143,606,345
    144,610,398
    145,359,524
    146,121,385
    147,178,221
    148,409,76
    149,156,413
    150,275,179
    151,609,371
    152,344,518
    153,409,530
    154,451,520
    155,546,486
    156,329,509
    157,290,477
    158,393,530
    159,437,525
    160,99,481
    161,491,201
    162,490,162
    163,503,532
    164,185,114
    165,609,411
    166,94,463
    167,505,208
    168,457,555
    169,489,540
    170,188,208
    171,195,256
    172,195,64
    173,524,454
    174,607,427
    175,356,114
    176,148,579
    177,196,106
    178,610,385
    179,590,235
    180,643,359
    181,303,128
    182,645,378
    183,424,528
    184,135,111
    185,473,549
    186,280,462
    187,559,463
    188,570,433
    189,485,124
    190,583,287
    191,279,516
    192,498,128
    193,553,475
    194,529,509
    195,262,146
    196,366,561
    197,444,114
    198,503,168
    199,306,538
    200,368,112
    201,140,566
    202,536,187
    203,540,496
    204,272,446
    205,561,205
    206,516,521
    207,576,275
    208,379,111
    209,390,110
    210,547,194
    211,532,552
    212,449,150
    213,172,80
    214,61,477
    215,464,154
    216,149,201
    217,116,528
    218,569,515
    219,145,101
    220,504,572
    221,220,50
    222,106,505
    223,592,476
    224,513,96
    225,129,551
    226,488,581
    227,643,424
    228,485,87
    229,530,103
    230,56,453
    231,521,137
    232,498,91
    233,602,333
    234,403,564
    235,638,446
    236,258,492
    237,276,139
    238,138,62
    239,90,445
    240,535,145
    241,515,174
    242,136,296
    243,144,276
    244,248,477
    245,124,606
    246,351,79
    247,675,332
    248,553,247
    249,554,532
    250,543,543
    251,444,78
    252,457,81
    253,605,257
    254,318,159
    255,370,77
    256,243,77
    257,343,116
    258,264,68
    259,105,578
    260,122,417
    261,175,294
    262,407,145
    263,352,185
    264,520,563
    265,420,76
    266,68,499
    267,95,563
    268,112,592
    269,603,442
    270,608,358
    271,645,396
    272,615,273
    273,447,44
    274,252,152
    275,158,188
    276,183,277
    277,565,448
    278,532,597
    279,402,110
    280,472,83
    281,365,183
    282,218,132
    283,561,256
    284,459,116
    285,117,184
    286,509,133
    287,354,595
    288,575,218
    289,121,369
    290,86,544
    291,86,390
    292,127,233
    293,624,290
    294,129,168
    295,237,450
    296,86,375
    297,526,181
    298,229,126
    299,159,46
    300,432,77
    301,143,154
    302,473,120
    303,240,40
    304,55,561
    305,316,123
    306,514,607
    307,87,428
    308,86,412
    309,486,51
    310,383,76
    311,396,75
    312,137,218
    313,153,258
    314,169,309
    315,183,31
    ENDDATA
    )
  end
  
end

app/views/admin/works/_form.html.erb
<%= form_for([:admin, @work]) do |f| %>
  <% if @work.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@work.errors.count, "error") %> prohibited this work from being saved:</h2>

      <ul>
      <% @work.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_area :title %>
  </div>
  <div class="field">
    <%= f.label :parent_id %><br>
    <%= f.collection_select :parent_id, Work.all(:order => "title"), :id, :title, :include_blank => true %>
  </div>
  <div class="field">
    <%= f.label :artist_id %><br>
    <%= f.collection_select :artist_id, Artist.all(:order => "name"), :id, :name, :include_blank => true %>
  </div>
  <div class="field">
    <%= f.label :medium %><br>
    <%= f.text_area :medium %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/admin/works/edit.html.erb
<h1>Editing work</h1>

<%= render 'form' %>

<%= link_to 'Show', [:admin, @work] %> |
<%= link_to 'Back', admin_works_path %>

app/views/admin/works/index.html.erb
<h1>Listing works</h1>
<style>td {border-bottom: 1px solid #ccc; border-left: 1px solid #ccc;}</style>
<table>
  <thead>
    <tr>
      <th>Spreadsheet ID</th>
      <th>Title</th>
      <th># Of Files</th>
      <th>Generation</th>
      <th># Of Descendents</th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @works.each do |work| %>
      <tr>
        <td><%= work.orig_id %>_<%= work.parent ? work.parent.orig_id : '0000' %></td>    
        <td><%= link_to work.title, [:admin, work] %></td>
        <td><%= work.work_representations.count %></td>        
        <td><%= work.depth %></td>
        <td><%= work.descendents.count %></td>
        <td><%= link_to 'Edit', edit_admin_work_path(work) %></td>
        <!--<td><%= link_to 'Destroy', [:admin, work], method: :delete, data: { confirm: 'Are you sure?' } %></td>-->
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Work', new_admin_work_path %>

app/views/admin/works/jsontree.html.erb
<h1>Treeview of Works</h1><div class="tree"><%= raw @treehtml.to_json %></div>

app/views/admin/works/new.html.erb
<h1>New work</h1>

<%= render 'form' %>

<%= link_to 'Back', admin_works_path %>

app/views/admin/works/show.html.erb
<p id="notice"><%= notice %></p>

<h1>
  <%= @work.title %>
</h1>

<p>
  <strong>Artist:</strong>
  <%= link_to h(@work.artist.name), @work.artist %>
  
  <strong>Medium:</strong>
  <%= @work.medium %>
</p>

<p>
  <h2>Experience the work:</h2>
  <ul class="experienceTheWork">
  <% if !@work.work_representations.empty? %>
      <% for wr in @work.work_representations %>
          <li class="<%= wr.fileext %>">
          <% case wr.fileext %>
           <% when 'jpg' %>
             <a href="<%= wr.url %>"><img src="<%= wr.url %>" width="400"/></a>
           <% when 'gif' %>
             <a href="<%= wr.url %>"><img src="<%= wr.url %>" width="400"/></a>      
           <% when 'png' %>
             <a href="<%= wr.url %>"><img src="<%= wr.url %>" width="400"/></a>         
           <% when 'doc' %>
             Download the original file: <br /><a href="<%= wr.url %>"><%= wr.url %></a>
           <% when 'docx' %>
             Download the original file: <br /><a href="<%= wr.url %>"><%= wr.url %></a>     
           <% when 'pdf' %>
             Download the original file: <br /><a href="<%= wr.url %>"><%= wr.url %></a>              
           <% when 'md' %>
             <p>Read the text here:</p>
             <div class="md-work"><%= raw(@markdown.render wr.text_body_markdown) %></div>
          <% else %>    
             <a href="<%= wr.url %>"><%= wr.url %></a>
          <% end %>

          <%=link_to h('(edit this entry)'), edit_admin_work_representation_path(wr) %></li>     
      <% end %>
  <% else %>
    <div class="noWorkRepresentations">This Work is Still in Progress</div>
  <% end %>
  </ul>
</p>

<div class="inspirationNavigation">
    <div class="inspiredby">
    <% unless @work.parent.nil? %>
    <p>
      <h4>Inspired by:</h4>
      <%= link_to h(@work.parent.title), @work.parent %>
    </p>
    <p>
        <h5>Other works inspired by <%= h(@work.parent.title) %></h5>
    </p>
    <% end %>
    </div>    
    
    <div class="inspired">
    <% unless @work.children.empty? %>
    <p>
      <h4>Inspired:</h4>
        <ul id="submenu">
          <% for work in @work.children %>
            <li><%= link_to h(work.title), work %></li>
          <% end %>
        </ul>
    </p>
    <% end %>
    </div>
</div>

<div style="clear:both;">
<%= link_to 'Edit', edit_admin_work_path(@work) %> |
<%= link_to 'Back', admin_works_path %>
</div>

app/views/admin/works/tree.html.erb
<h1>Treeview of Works</h1>
<style type="text/css">
.tree ul {
    list-style: none outside none;
}
.tree li a {
    line-height: 25px;
}
.tree > ul > li > a {
    color: #3B4C56;
    display: block;
    font-weight: normal;
    position: relative;
    text-decoration: none;
}
.tree li.parent > a {
    padding: 0 0 0 28px;
}
.tree li.parent > a:before {
    background-image: url("<%= asset_path 'plus_minus_icons.png' %>");
    background-position: 25px center;
     content: ""; 
    display: block;
    height: 21px;
    left: 0;
    position: absolute;
    top: 2px;
    vertical-align: middle;
    width: 23px;
}
.tree ul li.active > a:before {
    background-position: 0 center;
}
.tree ul li ul {
    border-left: 1px solid #D9DADB;
    display: none;
    margin: 0 0 0 12px;
    overflow: hidden;
    padding: 0 0 0 25px;
}
.tree ul li ul li {
    position: relative;
}
.tree ul li ul li:before {
    border-bottom: 1px dashed #E2E2E3;
    content: "";
    left: -20px;
    position: absolute;
    top: 12px;
    width: 15px;
}
</style>
<script type="text/javascript">
$( document ).ready( function( ) {
    $( '.tree li' ).each( function() {
        if( $( this ).children( 'ul' ).length > 0 ) {
            $( this ).addClass( 'parent' );     
        }
    });
 
    $( '.tree li.parent > a' ).click( function( ) {
        $( this ).parent().toggleClass( 'active' );
        $( this ).parent().children( 'ul' ).slideToggle( 'fast' );
    });
 
    $( '#all' ).click( function() {
 
        $( '.tree li' ).each( function() {
            $( this ).toggleClass( 'active' );
            $( this ).children( 'ul' ).slideToggle( 'fast' );
        });
    });
 
});
</script>
<div class="tree">
<%= raw @treehtml %>
</div>